import { StyleSheet } from "react-native";
import { COLORS, SIZES } from "../../../../constants/theme";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.pageBackgroundBrown,
    width: SIZES.width,
    height: SIZES.height,
  },
  upperMainContainer: {
    height: "50%",
    marginTop: (3 / 100) * SIZES.height,
  },
  upperRow: {
    marginHorizontal: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    top: 8,
    width: SIZES.width - 44,
    zIndex: 999,
  },
  image: {
    // resizeMode: "cover",
    width: "100%",
    height: "100%",
    // resizeMode: "contain",
    position: "absolute",
  },
  details: {
    marginTop: -7,
    backgroundColor: COLORS.lightWhite,
    width: SIZES.width,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  titleRow: {
    marginHorizontal: 20,
    // paddingBottom: 5,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: SIZES.width - 44,
    top: 20,
  },
  title: {
    fontFamily: "poppinsRegular400",
    fontSize: SIZES.large,
  },
  priceWrapper: {
    backgroundColor: COLORS.burlyWoodBrown,
    borderRadius: SIZES.large,
  },
  price: {
    paddingHorizontal: 10,
    fontFamily: "poppinsBold700",
    fontSize: SIZES.large,
  },
  ratingRow: {
    paddingBottom: 5,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: SIZES.width - 10,
    top: 5,
  },
  ratingText: {
    color: COLORS.gray3,
    fontFamily: "poppinsMedium500",
    paddingHorizontal: 5,
  },
  rating: {
    top: SIZES.large,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginHorizontal: SIZES.large,
  },
  rating2: {
    top: SIZES.large,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginHorizontal: SIZES.large,
    gap: 10,
  },
  descriptionWrapper: {
    marginTop: SIZES.large * 2,
    marginHorizontal: SIZES.large,
  },
  description: {
    fontFamily: "poppinsMedium500",
    fontSize: SIZES.large - 2,
  },
  descriptionStyle: {
    fontFamily: "poppinsRegular400",
    fontSize: SIZES.small,
    textAlign: "justify",
    marginBottom: SIZES.small,
  },
  location: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.burlyWoodBrown,
    padding: 5,
    borderRadius: SIZES.large,
    marginHorizontal: 12,
  },
  cartRow: {
    paddingBottom: 5,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: SIZES.width,
  },
  cartButton: {
    width: SIZES.width * 0.7,
    backgroundColor: COLORS.black,
    padding: SIZES.small / 2,
    borderRadius: SIZES.large,
    marginLeft: 12,
  },
  cartTitle: {
    marginLeft: SIZES.small,
    fontFamily: "poppinsBold700",
    fontSize: SIZES.medium,
    color: COLORS.lightWhite,
  },
  addToCart: {
    width: 37,
    height: 37,
    borderRadius: 50,
    margin: SIZES.small,
    backgroundColor: COLORS.black,
    alignItems: "center",
    justifyContent: "center",
  },
});
